# Generated by Django 3.0.3 on 2020-07-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedItem',
            new_name='UserProfileFeedItem',
        ),
    ]
